#pragma once

#if EZ_ENABLED(EZ_COMPILE_ENGINE_AS_DLL)
#  ifdef BUILDSYSTEM_BUILDING_DIRECTIONALTARGETINDICATORPLUGIN_LIB
#    define EZ_DIRECTIONALTARGETINDICATORPLUGIN_DLL EZ_DECL_EXPORT
#  else
#    define EZ_DIRECTIONALTARGETINDICATORPLUGIN_DLL EZ_DECL_IMPORT
#  endif
#else
#  define EZ_DIRECTIONALTARGETINDICATORPLUGIN_DLL
#endif
