ez_cmake_init()
ez_requires_editor()
if(NOT EZ_BUILD_MOVIES_PLUGIN)
  return()
endif()
ez_requires_miniaudio()
get_filename_component(PROJECT_NAME ${CMAKE_CURRENT_SOURCE_DIR} NAME_WE)
ez_create_target(LIBRARY ${PROJECT_NAME})
ez_link_target_qt(TARGET ${PROJECT_NAME} COMPONENTS Core Gui Widgets)
target_link_libraries(${PROJECT_NAME} PRIVATE EditorFramework EditorPluginScene)
add_dependencies(${PROJECT_NAME} MoviesPlugin)
