ez_cmake_init()
ez_requires_editor()
ez_requires_assimp()
get_filename_component(PROJECT_NAME ${CMAKE_CURRENT_SOURCE_DIR} NAME_WE)
ez_create_target(APPLICATION ${PROJECT_NAME})
ez_link_target_qt(TARGET ${PROJECT_NAME} COMPONENTS Core Gui Widgets Network)
target_include_directories(${PROJECT_NAME} PRIVATE "${CMAKE_CURRENT_SOURCE_DIR}/.." "${CMAKE_CURRENT_SOURCE_DIR}/../../EditorPlugins/Scene" "${CMAKE_CURRENT_SOURCE_DIR}/../../EditorPlugins/Assets")
target_sources(${PROJECT_NAME} PRIVATE "${CMAKE_CURRENT_SOURCE_DIR}/../EditorTest/TestClass/TestClass.cpp")
target_link_libraries(${PROJECT_NAME} PRIVATE TestFramework EditorFramework EditorEngineProcessFramework EditorPluginScene EditorPluginAssets GameEngine)
add_dependencies(${PROJECT_NAME} EditorEngineProcess EnginePluginAssets EnginePluginScene)
target_compile_definitions(${PROJECT_NAME} PRIVATE BLEND_SHAPE_TEST_DATA="${CMAKE_CURRENT_SOURCE_DIR}/../BlendShapeTest/Data" BLEND_SHAPE_TEST_OUTPUT="${CMAKE_SOURCE_DIR}/Workspace/BlendShapeEditorTest")
ez_ci_add_test(${PROJECT_NAME} NEEDS_HW_ACCESS)
