ez_cmake_init()
ez_requires(EZ_BUILD_UNITTESTS EZ_3RDPARTY_JOLT_SUPPORT)
ez_requires_renderer()
ez_create_target(APPLICATION SpringBonePluginTest)
target_link_libraries(SpringBonePluginTest PUBLIC TestFramework SpringBonePlugin)
if(TARGET ToolsFoundation)
  target_link_libraries(SpringBonePluginTest PRIVATE ToolsFoundation)
  target_compile_definitions(SpringBonePluginTest PRIVATE SPRINGBONE_EDITOR_TESTS)
endif()
ez_add_renderers(SpringBonePluginTest)
ez_ci_add_test(SpringBonePluginTest NEEDS_HW_ACCESS)
