ez_cmake_init()
ez_requires_editor()
ez_requires_assimp()
get_filename_component(PROJECT_NAME ${CMAKE_CURRENT_SOURCE_DIR} NAME_WE)
ez_create_target(APPLICATION ${PROJECT_NAME})
target_link_libraries(${PROJECT_NAME} PRIVATE TestFramework GameEngine EditorFramework EditorPluginAssets ModelImporter2)
ez_link_target_qt(TARGET ${PROJECT_NAME} COMPONENTS Core Gui Widgets)
ez_link_target_assimp(${PROJECT_NAME})
target_compile_definitions(${PROJECT_NAME} PRIVATE BLEND_SHAPE_TEST_DATA="${CMAKE_CURRENT_SOURCE_DIR}/Data")
ez_ci_add_test(${PROJECT_NAME} NEEDS_HW_ACCESS)
