ez_cmake_init()
if(NOT EZ_BUILD_MOVIES_PLUGIN)
  return()
endif()
ez_requires_renderer()
ez_requires_miniaudio()
get_filename_component(PROJECT_NAME ${CMAKE_CURRENT_SOURCE_DIR} NAME_WE)
ez_create_target(APPLICATION ${PROJECT_NAME})
target_link_libraries(${PROJECT_NAME} PRIVATE GameEngine MiniAudioPlugin MiniAudio)
add_dependencies(${PROJECT_NAME} MoviesPlugin)
ez_add_renderers(${PROJECT_NAME})
