#pragma once

#include <Foundation/Basics.h>

#if EZ_ENABLED(EZ_COMPILE_ENGINE_AS_DLL)
#  ifdef BUILDSYSTEM_BUILDING_SPRINGBONEPLUGIN_LIB
#    define EZ_SPRINGBONEPLUGIN_DLL EZ_DECL_EXPORT
#  else
#    define EZ_SPRINGBONEPLUGIN_DLL EZ_DECL_IMPORT
#  endif
#else
#  define EZ_SPRINGBONEPLUGIN_DLL
#endif
