#pragma once
#include <Foundation/Basics.h>
#include <Foundation/Configuration/Plugin.h>
#if EZ_ENABLED(EZ_COMPILE_ENGINE_AS_DLL)
#  ifdef BUILDSYSTEM_BUILDING_EDITORPLUGINGREYBOXEXTENDED_LIB
#    define EZ_EDITORPLUGINGREYBOXEXTENDED_DLL EZ_DECL_EXPORT
#  else
#    define EZ_EDITORPLUGINGREYBOXEXTENDED_DLL EZ_DECL_IMPORT
#  endif
#else
#  define EZ_EDITORPLUGINGREYBOXEXTENDED_DLL
#endif

